# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Carsinfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, model_type: str=None, model_name: str=None, transmission: str=None, fuel_type: str=None, trim: str=None, stock: int=None):  # noqa: E501
        """Carsinfo - a model defined in Swagger

        :param model_type: The model_type of this Carsinfo.  # noqa: E501
        :type model_type: str
        :param model_name: The model_name of this Carsinfo.  # noqa: E501
        :type model_name: str
        :param transmission: The transmission of this Carsinfo.  # noqa: E501
        :type transmission: str
        :param fuel_type: The fuel_type of this Carsinfo.  # noqa: E501
        :type fuel_type: str
        :param trim: The trim of this Carsinfo.  # noqa: E501
        :type trim: str
        :param stock: The stock of this Carsinfo.  # noqa: E501
        :type stock: int
        """
        self.swagger_types = {
            'model_type': str,
            'model_name': str,
            'transmission': str,
            'fuel_type': str,
            'trim': str,
            'stock': int
        }

        self.attribute_map = {
            'model_type': 'model_type',
            'model_name': 'model_name',
            'transmission': 'transmission',
            'fuel_type': 'fuel_type',
            'trim': 'trim',
            'stock': 'stock'
        }
        self._model_type = model_type
        self._model_name = model_name
        self._transmission = transmission
        self._fuel_type = fuel_type
        self._trim = trim
        self._stock = stock

    @classmethod
    def from_dict(cls, dikt) -> 'Carsinfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The carsinfo of this Carsinfo.  # noqa: E501
        :rtype: Carsinfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def model_type(self) -> str:
        """Gets the model_type of this Carsinfo.


        :return: The model_type of this Carsinfo.
        :rtype: str
        """
        return self._model_type

    @model_type.setter
    def model_type(self, model_type: str):
        """Sets the model_type of this Carsinfo.


        :param model_type: The model_type of this Carsinfo.
        :type model_type: str
        """
        allowed_values = ["SUVs", "Hatchback", "Sedan", "pickuptruck", "MUV", "off road"]  # noqa: E501
        if model_type not in allowed_values:
            raise ValueError(
                "Invalid value for `model_type` ({0}), must be one of {1}"
                .format(model_type, allowed_values)
            )

        self._model_type = model_type

    @property
    def model_name(self) -> str:
        """Gets the model_name of this Carsinfo.


        :return: The model_name of this Carsinfo.
        :rtype: str
        """
        return self._model_name

    @model_name.setter
    def model_name(self, model_name: str):
        """Sets the model_name of this Carsinfo.


        :param model_name: The model_name of this Carsinfo.
        :type model_name: str
        """

        self._model_name = model_name

    @property
    def transmission(self) -> str:
        """Gets the transmission of this Carsinfo.


        :return: The transmission of this Carsinfo.
        :rtype: str
        """
        return self._transmission

    @transmission.setter
    def transmission(self, transmission: str):
        """Sets the transmission of this Carsinfo.


        :param transmission: The transmission of this Carsinfo.
        :type transmission: str
        """
        allowed_values = ["manual", "automatic"]  # noqa: E501
        if transmission not in allowed_values:
            raise ValueError(
                "Invalid value for `transmission` ({0}), must be one of {1}"
                .format(transmission, allowed_values)
            )

        self._transmission = transmission

    @property
    def fuel_type(self) -> str:
        """Gets the fuel_type of this Carsinfo.


        :return: The fuel_type of this Carsinfo.
        :rtype: str
        """
        return self._fuel_type

    @fuel_type.setter
    def fuel_type(self, fuel_type: str):
        """Sets the fuel_type of this Carsinfo.


        :param fuel_type: The fuel_type of this Carsinfo.
        :type fuel_type: str
        """
        allowed_values = ["diesel", "petrol", "ev", "cng"]  # noqa: E501
        if fuel_type not in allowed_values:
            raise ValueError(
                "Invalid value for `fuel_type` ({0}), must be one of {1}"
                .format(fuel_type, allowed_values)
            )

        self._fuel_type = fuel_type

    @property
    def trim(self) -> str:
        """Gets the trim of this Carsinfo.


        :return: The trim of this Carsinfo.
        :rtype: str
        """
        return self._trim

    @trim.setter
    def trim(self, trim: str):
        """Sets the trim of this Carsinfo.


        :param trim: The trim of this Carsinfo.
        :type trim: str
        """
        allowed_values = ["SE", "DX", "GT"]  # noqa: E501
        if trim not in allowed_values:
            raise ValueError(
                "Invalid value for `trim` ({0}), must be one of {1}"
                .format(trim, allowed_values)
            )

        self._trim = trim

    @property
    def stock(self) -> int:
        """Gets the stock of this Carsinfo.


        :return: The stock of this Carsinfo.
        :rtype: int
        """
        return self._stock

    @stock.setter
    def stock(self, stock: int):
        """Sets the stock of this Carsinfo.


        :param stock: The stock of this Carsinfo.
        :type stock: int
        """

        self._stock = stock
